import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "./AuthProvider";
import { RegisterLink, LoginLink } from "@kinde-oss/kinde-auth-nextjs/components";
import {LogoutLink} from "@kinde-oss/kinde-auth-nextjs/components";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog Post Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <nav className="bg-green-500">
            <ul className="flex justify-center py-3 space-x-4">
              <li><Link href="/">home</Link></li>
              <li><Link href="/profile">profile</Link></li>
              <li><LoginLink>Sign in</LoginLink></li>
              <li><RegisterLink>Sign up</RegisterLink></li>
              <li><LogoutLink>Log out</LogoutLink></li>
            </ul>
          </nav>
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
